### ISSUE TITLE
addDocument function & test_AddDocument()

### ISSUE THREAD

**Issue by BigdraCo1** [felynoir/ept-template#2]
In  **DullNosql.sol**
![addDoc](https://github.com/felynoir/ept-template/assets/117558450/2a4be016-630d-4897-af16-7362c142e62b)
.
.
.
In  **DullNosql.t.sol**
![testcase](https://github.com/felynoir/ept-template/assets/117558450/7bda0bc6-3cb1-436f-801e-e3defa3ce93f)

สงสัยว่ามันผิดที่โคัดหรือ Testcase ครับพอดีเทสเคสอื่นรันได้ไม่มีปัญหา + function อื่นๆ เเต่เหมือนติดตรง Testcase เเรกไม่ก็ function เเรกครับ
ส่วนตัวผมคิดว่าใน **DullNosql.t.sol** บรรทัดที่ 5 มันควรจะมีค่าเท่ากับ 1 เเละ บรรทัดที่ 22 มีค่าเท่ากับ 2

**Comment by felynoir** [comment]
test case ถูกแล้วครับ บรรรทัดที่ 5 เป็น 1 , 22 เป็น 2

แต่โค้ดน่าจะผิดครับ ส่วน return น่าจะต้องเป็น `return size` ไม่ใช่ size -1

**Comment by BigdraCo1** [comment]
ขอบคุณคับเเก้เสร็จเเล้ว Test case ผ่านหมดเเล้วคับช่วย review code ได้มั้ยคับ

**DullNosql.sol**
![DullNosql_complete](https://github.com/felynoir/ept-template/assets/117558450/0d6026b3-f953-46d1-b59e-e04a6173a8fb)

**OrderPreservedMapping**
![OrderPreserved_complete](https://github.com/felynoir/ept-template/assets/117558450/d68a4bd1-cb15-4946-b51b-ca4d82b3f87f)

**Comment by felynoir** [comment]
จริงๆ แล้ว สำหรับ check input เราควรใช้ require/revert ครับ เพิ่มเติม https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require

เรื่องตัวแปรส่วนใหญ่จะใช้ pascal case ด้วย

ส่วน status = true เปลี่ยนเป็น updated = true ได้เลยครับ จะดีกว่า ประกาศตัวแปรเพิ่ม (deleted ด้วยเช่นกัน)

collection.documents.length กับ tmp_result.length เหมือนกันถ้า ประกาศตัวแปรแล้วใช้ร่วมกันน่าจะ save gas ได้

**Comment by BigdraCo1** [comment]
ขอบคุณครับสำหรับ Trick ดีๆครับ
